# Writes project.godot. The input map is generated because hand-typing Godot's
# InputEvent serialisation twenty-five times is how you get one silent typo.
import io

KEY = ("Object(InputEventKey,\"resource_local_to_scene\":false,\"resource_name\":\"\","
       "\"device\":-1,\"window_id\":0,\"alt_pressed\":false,\"shift_pressed\":false,"
       "\"ctrl_pressed\":false,\"meta_pressed\":false,\"pressed\":false,\"keycode\":0,"
       "\"physical_keycode\":{code},\"key_label\":0,\"unicode\":0,\"location\":0,"
       "\"echo\":false,\"script\":null)")

MOUSE = ("Object(InputEventMouseButton,\"resource_local_to_scene\":false,\"resource_name\":\"\","
         "\"device\":-1,\"window_id\":0,\"alt_pressed\":false,\"shift_pressed\":false,"
         "\"ctrl_pressed\":false,\"meta_pressed\":false,\"button_mask\":0,"
         "\"position\":Vector2(0, 0),\"global_position\":Vector2(0, 0),\"factor\":1.0,"
         "\"button_index\":{code},\"canceled\":false,\"pressed\":false,"
         "\"double_click\":false,\"script\":null)")

# Godot physical keycodes. Letters and digits are their ASCII uppercase values.
def k(ch): return ord(ch)
ESC, SHIFT, TAB, SPACE = 4194305, 4194325, 4194306, 32
LEFT, UP, RIGHT, DOWN = 4194319, 4194320, 4194321, 4194322
MOUSE_LEFT, MOUSE_RIGHT = 1, 2

ACTIONS = [
    ("move_up",     [("k", k('W')), ("k", UP)]),
    ("move_down",   [("k", k('S')), ("k", DOWN)]),
    ("move_left",   [("k", k('A')), ("k", LEFT)]),
    ("move_right",  [("k", k('D')), ("k", RIGHT)]),
    ("attack",      [("m", MOUSE_LEFT)]),
    ("interact",    [("k", k('E'))]),
    ("run",         [("k", SHIFT)]),
    ("swap_weapon", [("k", k('Q'))]),
    ("toggle_lamp", [("k", k('F'))]),
    ("open_pack",   [("k", k('I'))]),
    ("open_journal",[("k", k('J'))]),
    ("open_skills", [("k", k('K'))]),
    ("open_hints",  [("k", k('H'))]),
    ("toggle_mute", [("k", k('M'))]),
    ("pause",       [("k", ESC)]),
]
# Belt slots 1-9.
for i in range(1, 10):
    ACTIONS.append(("belt_%d" % i, [("k", ord(str(i)))]))


def action_block(name, events):
    parts = []
    for kind, code in events:
        parts.append((KEY if kind == "k" else MOUSE).format(code=code))
    body = ", ".join(parts)
    return '%s={\n"deadzone": 0.2,\n"events": [%s]\n}\n' % (name, body)


HEAD = '''; Engine configuration file.
; Generated by tools/gen_project_settings.py - re-run it rather than hand-editing
; the input map, but everything else here is safe to change in the editor.

config_version=5

[application]

config/name="Hollowmere"
config/description="A grimdark top-down RPG. You carry the only light."
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.7", "GL Compatibility")
config/icon="res://icon.svg"

[autoload]

EventBus="*res://src/core/event_bus.gd"
PlayerProgress="*res://src/core/player_progress.gd"
Inventory="*res://src/core/inventory.gd"
QuestLog="*res://src/core/quest_log.gd"
AudioDirector="*res://src/core/audio_director.gd"
SceneDirector="*res://src/core/scene_director.gd"

[display]

; The original ran at 576x360 and was scaled up with hard pixel edges. Raising
; this would resize every sprite in the game, all of which are drawn to this
; grid, so it is fixed.
window/size/viewport_width=576
window/size/viewport_height=360
window/size/window_width_override=1152
window/size/window_height_override=720
; "viewport" renders at 576x360 and scales the whole frame, so a pixel is always
; a pixel. "canvas_items" would let the UI drift off the grid.
window/stretch/mode="viewport"
window/stretch/aspect="keep"

[audio]

buses/default_bus_layout="res://default_bus_layout.tres"

[layer_names]

2d_physics/layer_1="World"
2d_physics/layer_2="Player"
2d_physics/layer_3="Enemy"
2d_physics/layer_4="PlayerHitbox"
2d_physics/layer_5="EnemyHitbox"
2d_physics/layer_6="Interactable"
2d_physics/layer_7="Pickup"
2d_physics/layer_8="Trigger"
2d_render/layer_1="World"
2d_render/layer_2="Light"

[rendering]

rendering_device/driver.windows="d3d12"
renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
; Nearest-neighbour. Without this every sprite is blurred on the way up.
textures/canvas_textures/default_texture_filter=0
2d/snap/snap_2d_transforms_to_pixel=true
2d/snap/snap_2d_vertices_to_pixel=true

[physics]

2d/default_gravity=0.0
3d/physics_engine="Jolt Physics"

[input]

'''

with io.open("project.godot", "w", encoding="utf-8", newline="\n") as f:
    f.write(HEAD)
    for name, events in ACTIONS:
        f.write(action_block(name, events))

print("wrote project.godot with %d actions" % len(ACTIONS))
